### PR TITLE
Feathers global debouncing, Poll and Event button disabling

### LINKED ISSUE #424: Event was created mulitiple times
**Describe the bug**

**To Reproduce**
image

**Expected behavior**

root cause: *commit_id*

### PR DESCRIPTION
**Pull request by StevenMalaihollo**
Closes #424

### CODE REVIEW

File: client/src/hooks/debounce.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import {HookContext} from '@feathersjs/feathers';
+
+const cache: Record<string, boolean> = {}
```
Comment (JakubC-projects) [inline client/src/hooks/debounce.ts:3]: I would personally use a set here
```typescript
const cache = new Set<string>()
```

**Review by JakubC-projects — APPROVED** [review]
